version: 2.1

jobs:
 build:
  docker:
   - image: holochain/holonix:latest
  steps:
   - checkout
   - run: nix-shell --run 'cargo test'

 deploy-crates:
  docker:
   - image: holochain/holonix:latest
  steps:
   - checkout
   - run:
      no_output_timeout: 20m
      command: nix-shell --run "hn-release-hook-publish 'tracing tracing_macros'"

workflows:
 version: 2.1
 test:
  jobs:
   - build
 deploy:
  jobs:
   - deploy-crates:
      filters:
       branches:
        ignore: /.*/
       tags:
        only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
